{% set name = "spymx-kernels" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 53dd29687033bf2f0f0b4e292de8b47da95626f73f54e2f35c6ddb1829f4c17f

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - spyder-kernels >=1.8.1

test:
  imports:
    - spymx_kernels
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/fumitoh/spymx-kernels
  summary: Jupyter kernels for Spyder plugin for modelx
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
