{% set name = "spymx-kernels" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spymx-kernels-{{ version }}.tar.gz
  sha256: 95a337f52a6506731f38dba44ab074f9f74bc9dfbd8756cbb1958e4f31afc5c8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - spyder-kernels >=1.8.1

test:
  imports:
    - spymx_kernels
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fumitoh/spymx-kernels
  summary: Jupyter kernels for Spyder plugin for modelx
  license: GPL-3.0-only
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - fumitoh
